// <auto-generated />
namespace CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addTimeAndSemesterTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTimeAndSemesterTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201605121908181_addTimeAndSemesterTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
